glslc src/shader/sun_direct_shade.comp -o bin/shader/sun_direct_shade.comp.spv
glslc src/shader/direct_shade.comp -o bin/shader/direct_shade.comp.spv
glslc src/shader/sun_direct_sampler.comp -o bin/shader/sun_direct_sampler.comp.spv
glslc src/shader/direct_sampler.comp -o bin/shader/direct_sampler.comp.spv
glslc src/shader/indirect_sampler.comp -o bin/shader/indirect_sampler.comp.spv
glslc src/shader/integrator.comp -o bin/shader/integrator.comp.spv
glslc src/shader/miss.comp -o bin/shader/miss.comp.spv
glslc src/shader/light_shade.comp -o bin/shader/light_shade.comp.spv
glslc src/shader/indirect_shade.comp -o bin/shader/indirect_shade.comp.spv
glslc src/shader/intersect_light.comp -o bin/shader/intersect_light.comp.spv
glslc src/shader/intersect_object.comp -o bin/shader/intersect_object.comp.spv
glslc src/shader/sampling.frag -o bin/shader/sampling.frag.spv
