glslc src/shader/direct_lambert_sun.comp -o bin/shader/direct_lambert_sun.comp.spv
glslc src/shader/direct_lambert.comp -o bin/shader/direct_lambert.comp.spv
glslc src/shader/direct_sampler_sun.comp -o bin/shader/direct_sampler_sun.comp.spv
glslc src/shader/direct_sampler.comp -o bin/shader/direct_sampler.comp.spv
glslc src/shader/indirect_sampler.comp -o bin/shader/indirect_sampler.comp.spv
glslc src/shader/integrator.comp -o bin/shader/integrator.comp.spv
glslc src/shader/miss.comp -o bin/shader/miss.comp.spv
glslc src/shader/light_shade.comp -o bin/shader/light_shade.comp.spv
glslc src/shader/indirect_lambert.comp -o bin/shader/indirect_lambert.comp.spv
glslc src/shader/intersect_light.comp -o bin/shader/intersect_light.comp.spv
glslc src/shader/intersect_object.comp -o bin/shader/intersect_object.comp.spv
glslc src/shader/sampling.frag -o bin/shader/sampling.frag.spv
