glslc src/shader/sun_direct_shade.comp -o shader/sun_direct_shade.comp.spv
glslc src/shader/direct_shade.comp -o shader/direct_shade.comp.spv
glslc src/shader/sun_direct_sampler.comp -o shader/sun_direct_sampler.comp.spv
glslc src/shader/direct_sampler.comp -o shader/direct_sampler.comp.spv
glslc src/shader/indirect_sampler.comp -o shader/indirect_sampler.comp.spv
glslc src/shader/integrator.comp -o shader/integrator.comp.spv
glslc src/shader/miss.comp -o shader/miss.comp.spv
glslc src/shader/light_shade.comp -o shader/light_shade.comp.spv
glslc src/shader/indirect_shade.comp -o shader/indirect_shade.comp.spv
glslc src/shader/intersect_light.comp -o shader/intersect_light.comp.spv
glslc src/shader/intersect_object.comp -o shader/intersect_object.comp.spv
glslc src/shader/sampling.frag -o shader/sampling.frag.spv
glslc src/shader/sampling.vert -o shader/sampling.vert.spv
